"""update task and project structure

Revision ID: b03b7efb848a
Revises: 3c5f74d76986
Create Date: 2025-01-01 18:35:58.498254

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b03b7efb848a'
down_revision: Union[str, None] = '3c5f74d76986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('users_ids', sa.ARRAY(sa.Integer()), nullable=True))
    op.drop_column('projects', 'status')
    op.drop_column('projects', 'priority')
    op.drop_column('projects', 'end_date')
    op.drop_column('projects', 'start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('projects', 'users_ids')
    # ### end Alembic commands ###
