"""
Revision ID: 03afb7851c2b
Revises: ca6f858e9b2d
Create Date: 2024-12-17 20:21:20.422334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03afb7851c2b'
down_revision = 'ca6f858e9b2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###